version: '3'
services:
  keycloak:
    image: quay.io/keycloak/keycloak:24.0.1
    environment:
      KEYCLOAK_ADMIN: AdminJim
      KEYCLOAK_ADMIN_PASSWORD: AdminJim
    ports:
      - 8080:8080
    command: start-dev
    depends_on:
      - postgres
  postgres:
    image: postgres
    environment:
      POSTGRES_DB: JimBeta
      POSTGRES_USER: AdminJim
      POSTGRES_PASSWORD: AdminJim
    ports:
      - 5432:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data
  app:
    build: .
    ports:
      - 3000:3000
    depends_on:
      - keycloak
    volumes:
      - .:/usr/src/app
      - /usr/src/node_modules

volumes:
  postgres_data: