version: '3'
services:
  postgres:
    image: postgres
    environment:
      POSTGRES_DB: JimBeta
      POSTGRES_USER: AdminJim
      POSTGRES_PASSWORD: AdminJim
    ports:
      - 5432:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: