version: '3'
services:
  mongodb:
    image: mongo
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: Jim
      MONGO_INITDB_ROOT_PASSWORD: Jim
    volumes:
      - mongodb_data:/data/db

  postgresql:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: Jim
      POSTGRES_PASSWORD: Jim
      POSTGRES_DB: postgresJim
    volumes:
      - postgresql_data:/var/lib/postgresql/data

volumes:
  mongodb_data:
  postgresql_data:
